apiVersion: apps/v1
kind: Deployment
metadata:
  name: cledgers
  labels:
    app: cledgers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cledgers
  template:
    metadata:
      labels:
        app: cledgers
    spec:
      containers:
        - name: cledgers
          image: registry.digitalocean.com/fdhenard/cledgers:latest
          ports:
            - containerPort: 3000
          env:
            - name: AKEYLESS_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: akeyless-creds
                  key: akeyless-access-id
            - name: AKEYLESS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: akeyless-creds
                  key: akeyless-access-key
